SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE account;
TRUNCATE TABLE role;
TRUNCATE TABLE users_roles;
TRUNCATE TABLE job;
TRUNCATE TABLE log;
TRUNCATE TABLE users_jobs;
SET REFERENTIAL_INTEGRITY TRUE;